// Code generated by "stringer -type HealthStatus -trimprefix HealthStatus"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HealthStatusUnknown-0]
	_ = x[HealthStatusHealthy-1]
	_ = x[HealthStatusDegraded-2]
	_ = x[HealthStatusError-3]
	_ = x[HealthStatusShutdown-4]
}

const _HealthStatus_name = "UnknownHealthyDegradedErrorShutdown"

var _HealthStatus_index = [...]uint8{0, 7, 14, 22, 27, 35}

func (i HealthStatus) String() string {
	if i < 0 || i >= HealthStatus(len(_HealthStatus_index)-1) {
		return "HealthStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HealthStatus_name[_HealthStatus_index[i]:_HealthStatus_index[i+1]]
}
