// Code generated by "stringer -type Phase -trimprefix Phase"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhaseWaiting-0]
	_ = x[PhaseInitializing-1]
	_ = x[PhaseRunning-2]
	_ = x[PhaseShuttingDown-3]
	_ = x[PhaseFinished-4]
	_ = x[PhaseFailed-5]
}

const _Phase_name = "WaitingInitializingRunningShuttingDownFinishedFailed"

var _Phase_index = [...]uint8{0, 7, 19, 26, 38, 46, 52}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
