// Code generated by "stringer -type Stage -trimprefix Stage"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StageWaiting-0]
	_ = x[StageInitializing-1]
	_ = x[StageRunning-2]
	_ = x[StageStopping-3]
	_ = x[StageFinished-4]
	_ = x[StageFailed-5]
}

const _Stage_name = "WaitingInitializingRunningStoppingFinishedFailed"

var _Stage_index = [...]uint8{0, 7, 19, 26, 34, 42, 48}

func (i Stage) String() string {
	if i < 0 || i >= Stage(len(_Stage_index)-1) {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[i]:_Stage_index[i+1]]
}
